# Generated by Django 2.1.2 on 2018-11-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
