# Generated by Django 2.1.2 on 2018-11-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
