# Generated by Django 2.1.2 on 2018-10-24 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Belonging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=4000)),
                ('state', models.CharField(choices=[('awful', 'awful'), ('very bad', 'very bad'), ('bad', 'bad'), ('regular', 'regular'), ('good', 'good'), ('very good', 'very good'), ('excelent', 'excelent')], default='good', max_length=10)),
                ('creation_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('phone', models.PositiveIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=4000)),
                ('date', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest_app.Category')),
                ('offered_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_app.Belonging')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_app.Owner')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='offered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_app.Owner'),
        ),
        migrations.AddField(
            model_name='offer',
            name='offered_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_app.Post'),
        ),
        migrations.AddField(
            model_name='offer',
            name='offered_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_app.Belonging'),
        ),
        migrations.AddField(
            model_name='belonging',
            name='belongs_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_app.Owner'),
        ),
        migrations.AddField(
            model_name='belonging',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest_app.Category'),
        ),
    ]
