# Generated by Django 2.1.2 on 2018-11-04 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0003_auto_20181104_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
