# Generated by Django 2.1.2 on 2018-11-12 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='img',
        ),
    ]
