# Generated by Django 2.1.2 on 2018-11-12 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20181112_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
