# Generated by Django 2.1.2 on 2018-11-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belongings', '0002_auto_20181105_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='belonging',
            name='img',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
